"""raw_payload to jsonb

Revision ID: be086e3a25d3
Revises: ed864f0e05fe
Create Date: 2026-07-15 12:27:22.269658

The model uses JSON().with_variant(JSONB(), "postgresql") (§6.7), which only
changes rendering under the postgresql dialect — autogenerate against sqlite
sees no diff, so this migration is hand-written rather than autogenerated.
No-op outside Postgres (sqlite dev already stores this as JSON/TEXT and needs
no change); an explicit USING cast is required for Postgres to reinterpret
the existing json column as jsonb.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = 'be086e3a25d3'
down_revision: Union[str, None] = 'ed864f0e05fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    if op.get_bind().dialect.name != "postgresql":
        return
    op.alter_column(
        "transactions",
        "raw_payload",
        type_=postgresql.JSONB(),
        postgresql_using="raw_payload::jsonb",
    )


def downgrade() -> None:
    if op.get_bind().dialect.name != "postgresql":
        return
    op.alter_column(
        "transactions",
        "raw_payload",
        type_=sa.JSON(),
        postgresql_using="raw_payload::json",
    )
