"""add token_version to users

Revision ID: ed864f0e05fe
Revises: 42254848b638
Create Date: 2026-07-15 12:22:36.124882
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ed864f0e05fe'
down_revision: Union[str, None] = '42254848b638'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows; NOT NULL without one would fail
    # on a non-empty table.
    op.add_column(
        'users',
        sa.Column('token_version', sa.Integer(), nullable=False, server_default='0'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_version')
    # ### end Alembic commands ###
